
<link type="text/css" rel="stylesheet" href="/gg/gg.css" media="all">
<link rel="shortcut icon" href="/gg/favicon.ico" type="image/x-icon">
<title>Lab GUID Assignment</title>

<script>
function rusure() {
    var txt;
    if (confirm("Warning: You should only do this if you just arrived to the lab session and are ready to begin or you are done with your lab entirely.  If you are sure click OK below otherwise, click Cancel.")) {
      window.location.href = "/gg/guidgrabber.cgi?operation=reset";
    }
}
</script>

<script>
function goBack() {
    window.history.back();
}
</script>
