
<link type="text/css" rel="stylesheet" href="/gg/gg.css" media="all">
<link rel="shortcut icon" href="/gg/favicon.ico" type="image/x-icon">
<title>Lab Manager</title>
<noscript>JavaScript must be enabled in your browser for this site to work correctly!</noscript>
<script>
function goBack() {
    window.history.back();
}
</script>

<style>
a:link {
    text-decoration: none;
    color: blue;
}

a:visited {
    text-decoration: none;
    color: blue;
}

a:hover {
    text-decoration: underline;
    color: blue;
}

a:active {
    text-decoration: underline;
    color: blue;
}
</style>
